apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-rcd
  namespace: system-uat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /tmp/data/guacamole/video
    server: 10.0.15.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacd-rcd
  namespace: system-uat
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  ports:
  - port: 4822
  selector:
    app:  guacamole-guacd
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  selector:
    matchLabels:
      app: guacamole-guacd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guacamole-guacd
    spec:
      containers:
      - image: docker.registry.local:5000/guacd:v1.${BUILD_NUMBER}
        name: guacamole-guacd
        ports:
        - containerPort: 4822
          name: guacd-rcd
        volumeMounts:
        - name: guacamole-rcd
          mountPath: /usr/src/video
      volumes:
      - name: guacd-rcd
        persistentVolumeClaim:
          claimName: guacd-rcd


