apiVersion: v1
kind: Service
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  ports:
  - port: 4822
  selector:
    app:  guacamole-guacd
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-guacd
  namespace: system-uat
spec:
  selector:
    matchLabels:
      app: guacamole-guacd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guacamole-guacd
    spec:
      containers:
      - image: docker.registry.local:5000/guacd:v1.${BUILD_NUMBER}
        name: guacamole-guacd
        ports:
        - containerPort: 4822
          name: guacamole-guacd


